# Web Scraping Using BeautifulSoup

In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [162]:
# scraping data from Nav page
url = 'https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav'
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
response = requests.get(url, headers = headers)
soup = BeautifulSoup(response.text)

company_name = []
rating = []
reviews = []
salaries = []
interviews = []
jobs = []
about = []


containers = soup.find_all('div', class_ = 'companyCardWrapper')

for container in containers:  
        company_name.append(container.find('h2').text.strip())
        rating.append(container.find('div', class_ = 'rating_text').text.strip())
        reviews.append(container.find_all('a', class_ = 'companyCardWrapper__ActionWrapper')[0].text.strip())
        salaries.append(container.find_all('a', class_ = 'companyCardWrapper__ActionWrapper')[1].text.strip())
        interviews.append(container.find_all('a', class_ = 'companyCardWrapper__ActionWrapper')[2].text.strip())
        jobs.append(container.find_all('a', class_ = 'companyCardWrapper__ActionWrapper')[3].text.strip())
        about.append(container.find('span', class_ = 'companyCardWrapper__interLinking').text.strip())
    
    
    
final_df = pd.DataFrame({
        'company' : company_name,
        'rating' : rating, 
        'review' : reviews,
        'interview' : interviews,
        'salary' : salaries,
        'jobs' : jobs,
        'about': about
    })
final_df

,company,rating,review,interview,salary,jobs,about
0,TCS,3.5,1L Reviews,11.5k Interviews,9.4L Salaries,897 Jobs,IT Services & Consulting | Bangalore / Bengalu...
1,Accenture,3.7,66.7k Reviews,8.9k Interviews,6.3L Salaries,32.6k Jobs,IT Services & Consulting | Bangalore / Bengalu...
2,Wipro,3.7,59.9k Reviews,6.3k Interviews,4.6L Salaries,7k Jobs,IT Services & Consulting | Bangalore / Bengalu...
3,Cognizant,3.7,56.9k Reviews,6.1k Interviews,5.8L Salaries,391 Jobs,IT Services & Consulting | Hyderabad / Secunde...
4,Capgemini,3.7,48.7k Reviews,5.2k Interviews,4.6L Salaries,2.2k Jobs,IT Services & Consulting | Bangalore / Bengalu...
5,HDFC Bank,3.8,46.4k Reviews,2.7k Interviews,1.4L Salaries,196 Jobs,Banking | Mumbai +1745 other locations
6,Infosys,3.5,44.8k Reviews,8.1k Interviews,5L Salaries,2.1k Jobs,IT Services & Consulting | Bangalore / Bengalu...
7,ICICI Bank,4.0,42.6k Reviews,2.8k Interviews,1.5L Salaries,1 Jobs,Banking | Mumbai +1399 other locations
8,HCLTech,3.4,41.8k Reviews,4.3k Interviews,3.6L Salaries,306 Jobs,IT Services & Consulting | Chennai +220 other ...
9,Tech Mahindra,3.4,40k Reviews,4.3k Interviews,2.8L Salaries,580 Jobs,IT Services & Consulting | Hyderabad / Secunde...
10,Genpact,3.7,38.1k Reviews,3.6k Interviews,2.2L Salaries,399 Jobs,IT Services & Consulting | Hyderabad / Secunde...
11,Teleperformance,3.9,34.2k Reviews,2.1k Interviews,93.1k Salaries,643 Jobs,BPO | Mumbai +244 other locations
12,Axis Bank,3.7,30k Reviews,1.8k Interviews,1L Salaries,831 Jobs,Banking | Mumbai +1464 other locations
13,Concentrix Corporation,3.6,29.7k Reviews,1.9k Interviews,1.3L Salaries,94 Jobs,BPO | Bangalore / Bengaluru +169 other locations
14,Jio,4.3,28.8k Reviews,3k Interviews,62.4k Salaries,59 Jobs,Telecom | Mumbai +1748 other locations
15,Amazon,4.0,28.8k Reviews,5.6k Interviews,1.4L Salaries,1.6k Jobs,Internet | Bangalore / Bengaluru +504 other lo...
16,iEnergizer,4.7,26.5k Reviews,908 Interviews,23.3k Salaries,33 Jobs,BPO | Noida +47 other locations
17,Reliance Retail,3.9,25.3k Reviews,1.8k Interviews,72.2k Salaries,94 Jobs,Retail | Mumbai +1115 other locations
18,IBM,3.9,24.3k Reviews,2.5k Interviews,2.1L Salaries,2.7k Jobs,IT Services & Consulting | Bangalore / Bengalu...
19,LTIMindtree,3.7,23.8k Reviews,3.1k Interviews,1.9L Salaries,446 Jobs,IT Services & Consulting | Bangalore / Bengalu...

In [163]:
# Scraping data from rest of the pages
for page in range(2, 20):
    company_name = []
    rating = []
    reviews = []
    salaries = []
    interviews = []
    jobs = []
    about = []
    
    url = f'https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page={page}'
    headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
    response = requests.get(url, headers = headers)
    soup = BeautifulSoup(response.text)

    containers = soup.find_all('div', class_ = 'companyCardWrapper')

    for container in containers:  
        company_name.append(container.find('h2').text.strip())
        rating.append(container.find('div', class_ = 'rating_text').text.strip())
        reviews.append(container.find_all('a', class_ = 'companyCardWrapper__ActionWrapper')[0].text.strip())
        salaries.append(container.find_all('a', class_ = 'companyCardWrapper__ActionWrapper')[1].text.strip())
        interviews.append(container.find_all('a', class_ = 'companyCardWrapper__ActionWrapper')[2].text.strip())
        jobs.append(container.find_all('a', class_ = 'companyCardWrapper__ActionWrapper')[3].text.strip())
        about.append(container.find('span', class_ = 'companyCardWrapper__interLinking').text.strip())
    
    
    
    df = pd.DataFrame({
        'company' : company_name,
        'rating' : rating, 
        'review' : reviews,
        'interview' : interviews,
        'salary' : salaries,
        'jobs' : jobs,
        'about': about
    })
    df

    final_df = pd.concat((final_df, df))


final_df

,company,rating,review,interview,salary,jobs,about
0,TCS,3.5,1L Reviews,11.5k Interviews,9.4L Salaries,897 Jobs,IT Services & Consulting | Bangalore / Bengalu...
1,Accenture,3.7,66.7k Reviews,8.9k Interviews,6.3L Salaries,32.6k Jobs,IT Services & Consulting | Bangalore / Bengalu...
2,Wipro,3.7,59.9k Reviews,6.3k Interviews,4.6L Salaries,7k Jobs,IT Services & Consulting | Bangalore / Bengalu...
3,Cognizant,3.7,56.9k Reviews,6.1k Interviews,5.8L Salaries,391 Jobs,IT Services & Consulting | Hyderabad / Secunde...
4,Capgemini,3.7,48.7k Reviews,5.2k Interviews,4.6L Salaries,2.2k Jobs,IT Services & Consulting | Bangalore / Bengalu...
...,...,...,...,...,...,...,...
15,Cholamandalam MS General Insurance,3.7,2.2k Reviews,111 Interviews,5.8k Salaries,-- Jobs,Insurance | Chennai +373 other locations
16,Aditya Birla Group,4.1,2.2k Reviews,222 Interviews,9.9k Salaries,2 Jobs,Metals & Mining | Mumbai +251 other locations
17,Lifestyle,4.3,2.2k Reviews,77 Interviews,6.8k Salaries,13 Jobs,Retail | Bangalore / Bengaluru +128 other loca...
18,Tata Advanced Systems,3.7,2.2k Reviews,171 Interviews,12k Salaries,4 Jobs,Defence & Aerospace | Bangalore / Bengaluru +4...
19,Mahindra Holidays & Resorts,3.5,2.2k Reviews,119 Interviews,5.9k Salaries,59 Jobs,Hospitality | Mumbai +108 other locations

(380, 7)